package com.pushit.api.security.domain.exception

class UserAlreadyExistsException : RuntimeException("User already exists")